// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package appdb

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Datapoint is an object representing the database table.
type Datapoint struct {
	ID               int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	AssetID          int32      `boil:"asset_id" json:"asset_id" toml:"asset_id" yaml:"asset_id"`
	SystemID         string     `boil:"system_id" json:"system_id" toml:"system_id" yaml:"system_id"`
	DeviceID         string     `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	ChannelID        string     `boil:"channel_id" json:"channel_id" toml:"channel_id" yaml:"channel_id"`
	Datapoint        string     `boil:"datapoint" json:"datapoint" toml:"datapoint" yaml:"datapoint"`
	Function         string     `boil:"function" json:"function" toml:"function" yaml:"function"`
	IsInput          bool       `boil:"is_input" json:"is_input" toml:"is_input" yaml:"is_input"`
	LastWrittenValue null.Int32 `boil:"last_written_value" json:"last_written_value,omitempty" toml:"last_written_value" yaml:"last_written_value,omitempty"`
	LastWrittenTime  null.Time  `boil:"last_written_time" json:"last_written_time,omitempty" toml:"last_written_time" yaml:"last_written_time,omitempty"`

	R *datapointR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L datapointL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DatapointColumns = struct {
	ID               string
	AssetID          string
	SystemID         string
	DeviceID         string
	ChannelID        string
	Datapoint        string
	Function         string
	IsInput          string
	LastWrittenValue string
	LastWrittenTime  string
}{
	ID:               "id",
	AssetID:          "asset_id",
	SystemID:         "system_id",
	DeviceID:         "device_id",
	ChannelID:        "channel_id",
	Datapoint:        "datapoint",
	Function:         "function",
	IsInput:          "is_input",
	LastWrittenValue: "last_written_value",
	LastWrittenTime:  "last_written_time",
}

var DatapointTableColumns = struct {
	ID               string
	AssetID          string
	SystemID         string
	DeviceID         string
	ChannelID        string
	Datapoint        string
	Function         string
	IsInput          string
	LastWrittenValue string
	LastWrittenTime  string
}{
	ID:               "datapoint.id",
	AssetID:          "datapoint.asset_id",
	SystemID:         "datapoint.system_id",
	DeviceID:         "datapoint.device_id",
	ChannelID:        "datapoint.channel_id",
	Datapoint:        "datapoint.datapoint",
	Function:         "datapoint.function",
	IsInput:          "datapoint.is_input",
	LastWrittenValue: "datapoint.last_written_value",
	LastWrittenTime:  "datapoint.last_written_time",
}

// Generated where

var DatapointWhere = struct {
	ID               whereHelperint64
	AssetID          whereHelperint32
	SystemID         whereHelperstring
	DeviceID         whereHelperstring
	ChannelID        whereHelperstring
	Datapoint        whereHelperstring
	Function         whereHelperstring
	IsInput          whereHelperbool
	LastWrittenValue whereHelpernull_Int32
	LastWrittenTime  whereHelpernull_Time
}{
	ID:               whereHelperint64{field: "\"abb_free_at_home\".\"datapoint\".\"id\""},
	AssetID:          whereHelperint32{field: "\"abb_free_at_home\".\"datapoint\".\"asset_id\""},
	SystemID:         whereHelperstring{field: "\"abb_free_at_home\".\"datapoint\".\"system_id\""},
	DeviceID:         whereHelperstring{field: "\"abb_free_at_home\".\"datapoint\".\"device_id\""},
	ChannelID:        whereHelperstring{field: "\"abb_free_at_home\".\"datapoint\".\"channel_id\""},
	Datapoint:        whereHelperstring{field: "\"abb_free_at_home\".\"datapoint\".\"datapoint\""},
	Function:         whereHelperstring{field: "\"abb_free_at_home\".\"datapoint\".\"function\""},
	IsInput:          whereHelperbool{field: "\"abb_free_at_home\".\"datapoint\".\"is_input\""},
	LastWrittenValue: whereHelpernull_Int32{field: "\"abb_free_at_home\".\"datapoint\".\"last_written_value\""},
	LastWrittenTime:  whereHelpernull_Time{field: "\"abb_free_at_home\".\"datapoint\".\"last_written_time\""},
}

// DatapointRels is where relationship names are stored.
var DatapointRels = struct {
	Asset string
}{
	Asset: "Asset",
}

// datapointR is where relationships are stored.
type datapointR struct {
	Asset *Asset `boil:"Asset" json:"Asset" toml:"Asset" yaml:"Asset"`
}

// NewStruct creates a new relationship struct
func (*datapointR) NewStruct() *datapointR {
	return &datapointR{}
}

func (r *datapointR) GetAsset() *Asset {
	if r == nil {
		return nil
	}
	return r.Asset
}

// datapointL is where Load methods for each relationship are stored.
type datapointL struct{}

var (
	datapointAllColumns            = []string{"id", "asset_id", "system_id", "device_id", "channel_id", "datapoint", "function", "is_input", "last_written_value", "last_written_time"}
	datapointColumnsWithoutDefault = []string{"asset_id", "system_id", "device_id", "channel_id", "datapoint", "function", "is_input"}
	datapointColumnsWithDefault    = []string{"id", "last_written_value", "last_written_time"}
	datapointPrimaryKeyColumns     = []string{"id"}
	datapointGeneratedColumns      = []string{}
)

type (
	// DatapointSlice is an alias for a slice of pointers to Datapoint.
	// This should almost always be used instead of []Datapoint.
	DatapointSlice []*Datapoint
	// DatapointHook is the signature for custom Datapoint hook methods
	DatapointHook func(context.Context, boil.ContextExecutor, *Datapoint) error

	datapointQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	datapointType                 = reflect.TypeOf(&Datapoint{})
	datapointMapping              = queries.MakeStructMapping(datapointType)
	datapointPrimaryKeyMapping, _ = queries.BindMapping(datapointType, datapointMapping, datapointPrimaryKeyColumns)
	datapointInsertCacheMut       sync.RWMutex
	datapointInsertCache          = make(map[string]insertCache)
	datapointUpdateCacheMut       sync.RWMutex
	datapointUpdateCache          = make(map[string]updateCache)
	datapointUpsertCacheMut       sync.RWMutex
	datapointUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var datapointAfterSelectHooks []DatapointHook

var datapointBeforeInsertHooks []DatapointHook
var datapointAfterInsertHooks []DatapointHook

var datapointBeforeUpdateHooks []DatapointHook
var datapointAfterUpdateHooks []DatapointHook

var datapointBeforeDeleteHooks []DatapointHook
var datapointAfterDeleteHooks []DatapointHook

var datapointBeforeUpsertHooks []DatapointHook
var datapointAfterUpsertHooks []DatapointHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Datapoint) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Datapoint) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Datapoint) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Datapoint) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Datapoint) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Datapoint) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Datapoint) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Datapoint) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Datapoint) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range datapointAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDatapointHook registers your hook function for all future operations.
func AddDatapointHook(hookPoint boil.HookPoint, datapointHook DatapointHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		datapointAfterSelectHooks = append(datapointAfterSelectHooks, datapointHook)
	case boil.BeforeInsertHook:
		datapointBeforeInsertHooks = append(datapointBeforeInsertHooks, datapointHook)
	case boil.AfterInsertHook:
		datapointAfterInsertHooks = append(datapointAfterInsertHooks, datapointHook)
	case boil.BeforeUpdateHook:
		datapointBeforeUpdateHooks = append(datapointBeforeUpdateHooks, datapointHook)
	case boil.AfterUpdateHook:
		datapointAfterUpdateHooks = append(datapointAfterUpdateHooks, datapointHook)
	case boil.BeforeDeleteHook:
		datapointBeforeDeleteHooks = append(datapointBeforeDeleteHooks, datapointHook)
	case boil.AfterDeleteHook:
		datapointAfterDeleteHooks = append(datapointAfterDeleteHooks, datapointHook)
	case boil.BeforeUpsertHook:
		datapointBeforeUpsertHooks = append(datapointBeforeUpsertHooks, datapointHook)
	case boil.AfterUpsertHook:
		datapointAfterUpsertHooks = append(datapointAfterUpsertHooks, datapointHook)
	}
}

// OneG returns a single datapoint record from the query using the global executor.
func (q datapointQuery) OneG(ctx context.Context) (*Datapoint, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single datapoint record from the query.
func (q datapointQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Datapoint, error) {
	o := &Datapoint{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "appdb: failed to execute a one query for datapoint")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Datapoint records from the query using the global executor.
func (q datapointQuery) AllG(ctx context.Context) (DatapointSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Datapoint records from the query.
func (q datapointQuery) All(ctx context.Context, exec boil.ContextExecutor) (DatapointSlice, error) {
	var o []*Datapoint

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "appdb: failed to assign all query results to Datapoint slice")
	}

	if len(datapointAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Datapoint records in the query using the global executor
func (q datapointQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Datapoint records in the query.
func (q datapointQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to count datapoint rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q datapointQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q datapointQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "appdb: failed to check if datapoint exists")
	}

	return count > 0, nil
}

// Asset pointed to by the foreign key.
func (o *Datapoint) Asset(mods ...qm.QueryMod) assetQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"asset_id\" = ?", o.AssetID),
	}

	queryMods = append(queryMods, mods...)

	return Assets(queryMods...)
}

// LoadAsset allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (datapointL) LoadAsset(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDatapoint interface{}, mods queries.Applicator) error {
	var slice []*Datapoint
	var object *Datapoint

	if singular {
		var ok bool
		object, ok = maybeDatapoint.(*Datapoint)
		if !ok {
			object = new(Datapoint)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDatapoint)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDatapoint))
			}
		}
	} else {
		s, ok := maybeDatapoint.(*[]*Datapoint)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDatapoint)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDatapoint))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &datapointR{}
		}
		if !queries.IsNil(object.AssetID) {
			args = append(args, object.AssetID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &datapointR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.AssetID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.AssetID) {
				args = append(args, obj.AssetID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`abb_free_at_home.asset`),
		qm.WhereIn(`abb_free_at_home.asset.asset_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Asset")
	}

	var resultSlice []*Asset
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Asset")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for asset")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for asset")
	}

	if len(assetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Asset = foreign
		if foreign.R == nil {
			foreign.R = &assetR{}
		}
		foreign.R.Datapoints = append(foreign.R.Datapoints, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.AssetID, foreign.AssetID) {
				local.R.Asset = foreign
				if foreign.R == nil {
					foreign.R = &assetR{}
				}
				foreign.R.Datapoints = append(foreign.R.Datapoints, local)
				break
			}
		}
	}

	return nil
}

// SetAssetG of the datapoint to the related item.
// Sets o.R.Asset to related.
// Adds o to related.R.Datapoints.
// Uses the global database handle.
func (o *Datapoint) SetAssetG(ctx context.Context, insert bool, related *Asset) error {
	return o.SetAsset(ctx, boil.GetContextDB(), insert, related)
}

// SetAsset of the datapoint to the related item.
// Sets o.R.Asset to related.
// Adds o to related.R.Datapoints.
func (o *Datapoint) SetAsset(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Asset) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"abb_free_at_home\".\"datapoint\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"asset_id"}),
		strmangle.WhereClause("\"", "\"", 2, datapointPrimaryKeyColumns),
	)
	values := []interface{}{related.AssetID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.AssetID, related.AssetID)
	if o.R == nil {
		o.R = &datapointR{
			Asset: related,
		}
	} else {
		o.R.Asset = related
	}

	if related.R == nil {
		related.R = &assetR{
			Datapoints: DatapointSlice{o},
		}
	} else {
		related.R.Datapoints = append(related.R.Datapoints, o)
	}

	return nil
}

// Datapoints retrieves all the records using an executor.
func Datapoints(mods ...qm.QueryMod) datapointQuery {
	mods = append(mods, qm.From("\"abb_free_at_home\".\"datapoint\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"abb_free_at_home\".\"datapoint\".*"})
	}

	return datapointQuery{q}
}

// FindDatapointG retrieves a single record by ID.
func FindDatapointG(ctx context.Context, iD int64, selectCols ...string) (*Datapoint, error) {
	return FindDatapoint(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindDatapoint retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDatapoint(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Datapoint, error) {
	datapointObj := &Datapoint{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"abb_free_at_home\".\"datapoint\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, datapointObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "appdb: unable to select from datapoint")
	}

	if err = datapointObj.doAfterSelectHooks(ctx, exec); err != nil {
		return datapointObj, err
	}

	return datapointObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Datapoint) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Datapoint) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("appdb: no datapoint provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(datapointColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	datapointInsertCacheMut.RLock()
	cache, cached := datapointInsertCache[key]
	datapointInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			datapointAllColumns,
			datapointColumnsWithDefault,
			datapointColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(datapointType, datapointMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(datapointType, datapointMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"abb_free_at_home\".\"datapoint\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"abb_free_at_home\".\"datapoint\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "appdb: unable to insert into datapoint")
	}

	if !cached {
		datapointInsertCacheMut.Lock()
		datapointInsertCache[key] = cache
		datapointInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Datapoint record using the global executor.
// See Update for more documentation.
func (o *Datapoint) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Datapoint.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Datapoint) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	datapointUpdateCacheMut.RLock()
	cache, cached := datapointUpdateCache[key]
	datapointUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			datapointAllColumns,
			datapointPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("appdb: unable to update datapoint, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"abb_free_at_home\".\"datapoint\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, datapointPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(datapointType, datapointMapping, append(wl, datapointPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to update datapoint row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to get rows affected by update for datapoint")
	}

	if !cached {
		datapointUpdateCacheMut.Lock()
		datapointUpdateCache[key] = cache
		datapointUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q datapointQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q datapointQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to update all for datapoint")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to retrieve rows affected for datapoint")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o DatapointSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DatapointSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("appdb: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), datapointPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"abb_free_at_home\".\"datapoint\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, datapointPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to update all in datapoint slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to retrieve rows affected all in update all datapoint")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Datapoint) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Datapoint) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("appdb: no datapoint provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(datapointColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	datapointUpsertCacheMut.RLock()
	cache, cached := datapointUpsertCache[key]
	datapointUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			datapointAllColumns,
			datapointColumnsWithDefault,
			datapointColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			datapointAllColumns,
			datapointPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("appdb: unable to upsert datapoint, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(datapointPrimaryKeyColumns))
			copy(conflict, datapointPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"abb_free_at_home\".\"datapoint\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(datapointType, datapointMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(datapointType, datapointMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "appdb: unable to upsert datapoint")
	}

	if !cached {
		datapointUpsertCacheMut.Lock()
		datapointUpsertCache[key] = cache
		datapointUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Datapoint record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Datapoint) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Datapoint record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Datapoint) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("appdb: no Datapoint provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), datapointPrimaryKeyMapping)
	sql := "DELETE FROM \"abb_free_at_home\".\"datapoint\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to delete from datapoint")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to get rows affected by delete for datapoint")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q datapointQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q datapointQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("appdb: no datapointQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to delete all from datapoint")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to get rows affected by deleteall for datapoint")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o DatapointSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DatapointSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(datapointBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), datapointPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"abb_free_at_home\".\"datapoint\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, datapointPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to delete all from datapoint slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to get rows affected by deleteall for datapoint")
	}

	if len(datapointAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Datapoint) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("appdb: no Datapoint provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Datapoint) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDatapoint(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DatapointSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("appdb: empty DatapointSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DatapointSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DatapointSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), datapointPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"abb_free_at_home\".\"datapoint\".* FROM \"abb_free_at_home\".\"datapoint\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, datapointPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "appdb: unable to reload all in DatapointSlice")
	}

	*o = slice

	return nil
}

// DatapointExistsG checks if the Datapoint row exists.
func DatapointExistsG(ctx context.Context, iD int64) (bool, error) {
	return DatapointExists(ctx, boil.GetContextDB(), iD)
}

// DatapointExists checks if the Datapoint row exists.
func DatapointExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"abb_free_at_home\".\"datapoint\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "appdb: unable to check if datapoint exists")
	}

	return exists, nil
}

// Exists checks if the Datapoint row exists.
func (o *Datapoint) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DatapointExists(ctx, exec, o.ID)
}
